version: '3'

services:
  server:
    container_name: target_server
    build: .
    volumes:
      - .:/server_dir/
    working_dir: /server_dir/
    restart: always
    ports:
      - "55555:50000"
    command: ['python','main.py']